jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
        server-id: github
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B compile
    - continue-on-error: true
      name: Run tests
      run: mvn -B test
    - continue-on-error: true
      name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___pipeline.yml
permissions:
  contents: write
